junit_tests(
    name = "DFATest",
    dependencies = [
        "src/main/scala/lucassonnabend/finiteautomata:finiteautomata",
        "3rdparty:scalatest",
    ],
    sources = [
        "DFATest.scala",
        "TestRegexes.scala",
    ],
)

junit_tests(
    name = "NFATest",
    dependencies = [
        "src/main/scala/lucassonnabend/finiteautomata:finiteautomata",
        "3rdparty:scalatest",
    ],
    sources = [
        "NFATest.scala",
        "TestRegexes.scala",
    ],
)

junit_tests(
    name = "SimlifierTest",
    dependencies = [],
    sources = [
        "RegexSimplifierTest.scala",
        "TestRegexes.scala",
    ],
)
