scala_library(
	name = "finiteautomata",
	sources=[
	    "DFA.scala",
	    "NFA.scala",
	    "ParsingException.scala",
	    "RegexSimplifier.scala"
    ],
    provides = artifact(
        org = "lucassonnabend",
        name = "finiteautomata",
        repo = public,
    )
)
