scala_library(
	name = "finiteautomata",
	sources = [
		"DFA.scala",
		"NFA.scala",
		"ParsingException.scala",
		"RegexSimplifier.scala"
	],
	provides = artifact(
		org = "lucassonnabend.finiteautomata",
		name = "finiteautomata",
		repo = public,
	)
)
