load("@io_bazel_rules_scala//scala:scala.bzl", "scala_library", "scala_binary", "scala_test")

scala_library(
	name = "finiteAutomata",
	srcs = [
		"DFA.scala",
		"NFA.scala",
		"ParsingException.scala",
		"RegexSimplifier.scala",
	],
	visibility = ["//visibility:public"],
)
